# Generated by Django 5.1.4 on 2024-12-19 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar', models.CharField(max_length=10)),
                ('tip', models.CharField(choices=[('single', 'Cameră Single'), ('double', 'Cameră Dublă'), ('triple', 'Cameră Triplă')], max_length=10)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('data_sosire', models.DateField()),
                ('data_plecare', models.DateField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pensiune.camera')),
            ],
        ),
    ]
